export PATH=$HOME/.nodebrew/current/bin:$PATH
alias la='ls -a'
alias vi='nvim'
alias vz='vi ~/.config/zsh/.zshrc'
alias vm='vi ~/.vimrc'
alias vtx='vi ~/.tmux.conf'
alias soz='source ~/.config/zsh/.zshrc'
alias tmuxks='tmux kill-server'
alias tmuxk='tmux kill-session'
